In [58]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings("ignore")

In [59]:
df=pd.read_csv("bank.csv")
df.head(2)

age  job  marital  education  default  balance  housing  loan  contact  \
0   59    0        1          1        0     2343        1     0        2   
1   56    0        1          1        0       45        0     0        2   

   day  month  duration  campaign  pdays  previous  poutcome  deposit  
0    5      8      1042         1     -1         0         3        1  
1    5      8      1467         1     -1         0         3        1

In [60]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11162 entries, 0 to 11161
Data columns (total 17 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   age        11162 non-null  int64
 1   job        11162 non-null  int64
 2   marital    11162 non-null  int64
 3   education  11162 non-null  int64
 4   default    11162 non-null  int64
 5   balance    11162 non-null  int64
 6   housing    11162 non-null  int64
 7   loan       11162 non-null  int64
 8   contact    11162 non-null  int64
 9   day        11162 non-null  int64
 10  month      11162 non-null  int64
 11  duration   11162 non-null  int64
 12  campaign   11162 non-null  int64
 13  pdays      11162 non-null  int64
 14  previous   11162 non-null  int64
 15  poutcome   11162 non-null  int64
 16  deposit    11162 non-null  int64
dtypes: int64(17)
memory usage: 1.4 MB


In [61]:
df.describe()

age           job       marital     education       default  \
count  11162.000000  11162.000000  11162.000000  11162.000000  11162.000000   
mean      41.231948      4.487905      1.199337      1.285164      0.015051   
std       11.913369      3.225132      0.625552      0.749478      0.121761   
min       18.000000      0.000000      0.000000      0.000000      0.000000   
25%       32.000000      1.000000      1.000000      1.000000      0.000000   
50%       39.000000      4.000000      1.000000      1.000000      0.000000   
75%       49.000000      7.000000      2.000000      2.000000      0.000000   
max       95.000000     11.000000      2.000000      3.000000      1.000000   

            balance       housing          loan       contact           day  \
count  11162.000000  11162.000000  11162.000000  11162.000000  11162.000000   
mean    1528.538524      0.473123      0.130801      0.489697     15.658036   
std     3225.413326      0.499299      0.337198      0.818724      8.420740   
min    -6847.000000      0.000000      0.000000      0.000000      1.000000   
25%      122.000000      0.000000      0.000000      0.000000      8.000000   
50%      550.000000      0.000000      0.000000      0.000000     15.000000   
75%     1708.000000      1.000000      0.000000      1.000000     22.000000   
max    81204.000000      1.000000      1.000000      2.000000     31.000000   

              month      duration      campaign         pdays      previous  \
count  11162.000000  11162.000000  11162.000000  11162.000000  11162.000000   
mean       5.445709    371.993818      2.508421     51.330407      0.832557   
std        3.191939    347.128386      2.722077    108.758282      2.292007   
min        0.000000      2.000000      1.000000     -1.000000      0.000000   
25%        3.000000    138.000000      1.000000     -1.000000      0.000000   
50%        6.000000    255.000000      2.000000     -1.000000      0.000000   
75%        8.000000    496.000000      3.000000     20.750000      1.000000   
max       11.000000   3881.000000     63.000000    854.000000     58.000000   

           poutcome       deposit  
count  11162.000000  11162.000000  
mean       2.477782      0.473840  
std        1.002952      0.499338  
min        0.000000      0.000000  
25%        2.000000      0.000000  
50%        3.000000      0.000000  
75%        3.000000      1.000000  
max        3.000000      1.000000

In [62]:
features=df.drop("deposit",axis=1)
target=df["deposit"]

In [63]:
from sklearn.model_selection import train_test_split
# putting stratify because target is imbalanced. 
xtrain,xtest,ytrain,ytest=train_test_split(features,target,random_state=10,test_size=0.15)
print(f"Training data : {xtrain.shape, ytrain.shape}" )
print(f"Testing data : {xtest.shape, ytest.shape}" )

Training data : ((9487, 16), (9487,))
Testing data : ((1675, 16), (1675,))


In [64]:
# Data Scaling
from sklearn.preprocessing import StandardScaler
ss=StandardScaler()
xtrain=ss.fit_transform(xtrain)
xtest=ss.transform(xtest)

In [65]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report,confusion_matrix

In [66]:
def mymodel(model):
    model.fit(xtrain,ytrain)
    ypred=model.predict(xtest)
    # checking overfitting underfitting
    training_score=model.score(xtrain,ytrain)
    testing_score=model.score(xtest,ytest)
    print(f"Training Score : {training_score}")
    print(f"Testing Score : {testing_score}")
    print(f"Confusion Matrix : \n{confusion_matrix(ytest,ypred)}")
    # classification report
    print(f"Classification Report : \n{classification_report(ytest,ypred)}")
    return model

In [67]:
# Logistic Regression
# Decision Tree
# Pruning Techniques- grid Search CV
# Random Forest
# 

In [68]:
from sklearn.ensemble import AdaBoostClassifier # Adaptive Boosting Classifier
mymodel(AdaBoostClassifier())
'''

'''

Training Score : 0.8264994202593022
Testing Score : 0.822089552238806
Confusion Matrix : 
[[722 151]
 [147 655]]
Classification Report : 
              precision    recall  f1-score   support

           0       0.83      0.83      0.83       873
           1       0.81      0.82      0.81       802

    accuracy                           0.82      1675
   macro avg       0.82      0.82      0.82      1675
weighted avg       0.82      0.82      0.82      1675



'\n\n'

In [69]:
mymodel(AdaBoostClassifier(n_estimators=40))
# n_estimators gives number of decision trees.It depends on the number of features we have.

Training Score : 0.8212290502793296
Testing Score : 0.8202985074626866
Confusion Matrix : 
[[721 152]
 [149 653]]
Classification Report : 
              precision    recall  f1-score   support

           0       0.83      0.83      0.83       873
           1       0.81      0.81      0.81       802

    accuracy                           0.82      1675
   macro avg       0.82      0.82      0.82      1675
weighted avg       0.82      0.82      0.82      1675



AdaBoostClassifier(n_estimators=40)

In [86]:
# Gradient Boosting Classifier
from sklearn.ensemble import GradientBoostingClassifier
mymodel(GradientBoostingClassifier(n_estimators=40))

Training Score : 0.8380942342152419
Testing Score : 0.8364179104477611
Confusion Matrix : 
[[715 158]
 [116 686]]
Classification Report : 
              precision    recall  f1-score   support

           0       0.86      0.82      0.84       873
           1       0.81      0.86      0.83       802

    accuracy                           0.84      1675
   macro avg       0.84      0.84      0.84      1675
weighted avg       0.84      0.84      0.84      1675



GradientBoostingClassifier(n_estimators=40)

In [88]:
# Extreme GradientBoosting
# XGBoost
!pip install xgboost

Defaulting to user installation because normal site-packages is not writeable


In [102]:
from xgboost import XGBClassifier
mymodel(XGBClassifier(n_estimators=80))

Training Score : 0.9511963739854538
Testing Score : 0.8501492537313433
Confusion Matrix : 
[[729 144]
 [107 695]]
Classification Report : 
              precision    recall  f1-score   support

           0       0.87      0.84      0.85       873
           1       0.83      0.87      0.85       802

    accuracy                           0.85      1675
   macro avg       0.85      0.85      0.85      1675
weighted avg       0.85      0.85      0.85      1675



XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=80, n_jobs=None,
              num_parallel_tree=None, random_state=None, ...)

In [ ]:
pip install --upgrade xgboost

In [ ]:
pip install --upgrade scikit-learn==1.02