In [1]:
import numpy as np # 
import pandas as pd # 
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings("ignore")

In [3]:
df=pd.read_csv("bank.csv")
df.head()

age  job  marital  education  default  balance  housing  loan  contact  \
0   59    0        1          1        0     2343        1     0        2   
1   56    0        1          1        0       45        0     0        2   
2   41    9        1          1        0     1270        1     0        2   
3   55    7        1          1        0     2476        1     0        2   
4   54    0        1          2        0      184        0     0        2   

   day  month  duration  campaign  pdays  previous  poutcome  deposit  
0    5      8      1042         1     -1         0         3        1  
1    5      8      1467         1     -1         0         3        1  
2    5      8      1389         1     -1         0         3        1  
3    5      8       579         1     -1         0         3        1  
4    5      8       673         2     -1         0         3        1

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11162 entries, 0 to 11161
Data columns (total 17 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   age        11162 non-null  int64
 1   job        11162 non-null  int64
 2   marital    11162 non-null  int64
 3   education  11162 non-null  int64
 4   default    11162 non-null  int64
 5   balance    11162 non-null  int64
 6   housing    11162 non-null  int64
 7   loan       11162 non-null  int64
 8   contact    11162 non-null  int64
 9   day        11162 non-null  int64
 10  month      11162 non-null  int64
 11  duration   11162 non-null  int64
 12  campaign   11162 non-null  int64
 13  pdays      11162 non-null  int64
 14  previous   11162 non-null  int64
 15  poutcome   11162 non-null  int64
 16  deposit    11162 non-null  int64
dtypes: int64(17)
memory usage: 1.4 MB


In [15]:
df[df["pdays"]==-1]["pdays"]

0       -1
1       -1
2       -1
3       -1
4       -1
        ..
11156   -1
11157   -1
11158   -1
11159   -1
11161   -1
Name: pdays, Length: 8324, dtype: int64

In [17]:
features=df.drop("deposit",axis=1)
target=df["deposit"]

In [19]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(features,target,test_size=0.2,random_state=1)

In [23]:
from sklearn.preprocessing import StandardScaler
ss=StandardScaler()
xtrain=ss.fit_transform(xtrain)
xtest=ss.transform(xtest)

In [25]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [27]:
def mymodel(model):
    model.fit(xtrain,ytrain)
    ypred=model.predict(xtest)
    train_score=model.score(xtrain,ytrain)
    test_score=model.score(xtest,ytest)
    print(f"Training Score : {train_score}")
    print(f"Testing Score : {test_score}")
    print(f"Confusion Matrix : \n{confusion_matrix(ytest,ypred)}")
    print(f"Classification Report : \n{classification_report(ytest,ypred)}")
    return model

In [29]:
mymodel(DecisionTreeClassifier())

Training Score : 1.0
Testing Score : 0.7823555754590238
Confusion Matrix : 
[[932 233]
 [253 815]]
Classification Report : 
              precision    recall  f1-score   support

           0       0.79      0.80      0.79      1165
           1       0.78      0.76      0.77      1068

    accuracy                           0.78      2233
   macro avg       0.78      0.78      0.78      2233
weighted avg       0.78      0.78      0.78      2233



DecisionTreeClassifier()

In [31]:
from sklearn.ensemble import AdaBoostClassifier
mymodel(AdaBoostClassifier())

Training Score : 0.8276402732668832
Testing Score : 0.8199731303179579
Confusion Matrix : 
[[989 176]
 [226 842]]
Classification Report : 
              precision    recall  f1-score   support

           0       0.81      0.85      0.83      1165
           1       0.83      0.79      0.81      1068

    accuracy                           0.82      2233
   macro avg       0.82      0.82      0.82      2233
weighted avg       0.82      0.82      0.82      2233



AdaBoostClassifier()

In [35]:
mymodel(AdaBoostClassifier(n_estimators=30))

Training Score : 0.8198006495688207
Testing Score : 0.8150470219435737
Confusion Matrix : 
[[974 191]
 [222 846]]
Classification Report : 
              precision    recall  f1-score   support

           0       0.81      0.84      0.83      1165
           1       0.82      0.79      0.80      1068

    accuracy                           0.82      2233
   macro avg       0.82      0.81      0.81      2233
weighted avg       0.82      0.82      0.81      2233



AdaBoostClassifier(n_estimators=30)

In [41]:
from sklearn.ensemble import GradientBoostingClassifier
mymodel(GradientBoostingClassifier(n_estimators=30, learning_rate=1.0))

Training Score : 0.8784858326800313
Testing Score : 0.8351992834751455
Confusion Matrix : 
[[974 191]
 [177 891]]
Classification Report : 
              precision    recall  f1-score   support

           0       0.85      0.84      0.84      1165
           1       0.82      0.83      0.83      1068

    accuracy                           0.84      2233
   macro avg       0.83      0.84      0.83      2233
weighted avg       0.84      0.84      0.84      2233



GradientBoostingClassifier(learning_rate=1.0, n_estimators=30)

In [45]:
# XGBoost - extreme gradient boosting
!pip install xgboost

In [51]:
from xgboost import XGBClassifier
mymodel(XGBClassifier(n_estimators=70))

Training Score : 0.9396348975249188
Testing Score : 0.8495297805642633
Confusion Matrix : 
[[973 192]
 [144 924]]
Classification Report : 
              precision    recall  f1-score   support

           0       0.87      0.84      0.85      1165
           1       0.83      0.87      0.85      1068

    accuracy                           0.85      2233
   macro avg       0.85      0.85      0.85      2233
weighted avg       0.85      0.85      0.85      2233



XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=70, n_jobs=None,
              num_parallel_tree=None, random_state=None, ...)