In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings("ignore")

In [5]:
df=pd.read_csv("winequality-red.csv",sep=";")
df.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5  
3      9.8        6  
4      9.4        5

In [ ]:
# Ensemble techniques - Bagging (Bootstrap Aggregation), parallelized

In [7]:
df.info() #jkkkjlll

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1599 entries, 0 to 1598
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   fixed acidity         1599 non-null   float64
 1   volatile acidity      1599 non-null   float64
 2   citric acid           1599 non-null   float64
 3   residual sugar        1599 non-null   float64
 4   chlorides             1599 non-null   float64
 5   free sulfur dioxide   1599 non-null   float64
 6   total sulfur dioxide  1599 non-null   float64
 7   density               1599 non-null   float64
 8   pH                    1599 non-null   float64
 9   sulphates             1599 non-null   float64
 10  alcohol               1599 non-null   float64
 11  quality               1599 non-null   int64  
dtypes: float64(11), int64(1)
memory usage: 150.0 KB


In [9]:
df.describe()

fixed acidity  volatile acidity  citric acid  residual sugar  \
count    1599.000000       1599.000000  1599.000000     1599.000000   
mean        8.319637          0.527821     0.270976        2.538806   
std         1.741096          0.179060     0.194801        1.409928   
min         4.600000          0.120000     0.000000        0.900000   
25%         7.100000          0.390000     0.090000        1.900000   
50%         7.900000          0.520000     0.260000        2.200000   
75%         9.200000          0.640000     0.420000        2.600000   
max        15.900000          1.580000     1.000000       15.500000   

         chlorides  free sulfur dioxide  total sulfur dioxide      density  \
count  1599.000000          1599.000000           1599.000000  1599.000000   
mean      0.087467            15.874922             46.467792     0.996747   
std       0.047065            10.460157             32.895324     0.001887   
min       0.012000             1.000000              6.000000     0.990070   
25%       0.070000             7.000000             22.000000     0.995600   
50%       0.079000            14.000000             38.000000     0.996750   
75%       0.090000            21.000000             62.000000     0.997835   
max       0.611000            72.000000            289.000000     1.003690   

                pH    sulphates      alcohol      quality  
count  1599.000000  1599.000000  1599.000000  1599.000000  
mean      3.311113     0.658149    10.422983     5.636023  
std       0.154386     0.169507     1.065668     0.807569  
min       2.740000     0.330000     8.400000     3.000000  
25%       3.210000     0.550000     9.500000     5.000000  
50%       3.310000     0.620000    10.200000     6.000000  
75%       3.400000     0.730000    11.100000     6.000000  
max       4.010000     2.000000    14.900000     8.000000

In [11]:
features=df.drop("quality",axis=1)
target=df["quality"]

In [13]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(features,target,test_size=0.2,random_state=1)

In [18]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [20]:
def mymodel(model):
    model.fit(xtrain,ytrain)
    ypred=model.predict(xtest)
    train_score=model.score(xtrain,ytrain)
    test_score=model.score(xtest,ytest)
    print(f"Training Score : {train_score}")
    print(f"Testing Score : {test_score}")
    print(f"Confusion Matrix : \n{confusion_matrix(ytest,ypred)}")
    print(f"Classification Report : \n{classification_report(ytest,ypred)}")
    return model

In [22]:
df["quality"].value_counts()

quality
5    681
6    638
7    199
4     53
8     18
3     10
Name: count, dtype: int64

In [24]:
mymodel(DecisionTreeClassifier())

Training Score : 1.0
Testing Score : 0.6375
Confusion Matrix : 
[[  0   0   1   0   0   0]
 [  0   2   5   6   0   0]
 [  0   4 102  28   6   0]
 [  0   0  37  84  10   3]
 [  0   1   4  10  15   0]
 [  0   0   0   0   1   1]]
Classification Report : 
              precision    recall  f1-score   support

           3       0.00      0.00      0.00         1
           4       0.29      0.15      0.20        13
           5       0.68      0.73      0.71       140
           6       0.66      0.63      0.64       134
           7       0.47      0.50      0.48        30
           8       0.25      0.50      0.33         2

    accuracy                           0.64       320
   macro avg       0.39      0.42      0.39       320
weighted avg       0.63      0.64      0.63       320



DecisionTreeClassifier()

In [28]:
mymodel(RandomForestClassifier())

Training Score : 1.0
Testing Score : 0.725
Confusion Matrix : 
[[  0   0   1   0   0   0]
 [  0   1   8   4   0   0]
 [  0   0 116  22   2   0]
 [  0   1  26 101   6   0]
 [  0   0   2  15  13   0]
 [  0   0   0   0   1   1]]
Classification Report : 
              precision    recall  f1-score   support

           3       0.00      0.00      0.00         1
           4       0.50      0.08      0.13        13
           5       0.76      0.83      0.79       140
           6       0.71      0.75      0.73       134
           7       0.59      0.43      0.50        30
           8       1.00      0.50      0.67         2

    accuracy                           0.72       320
   macro avg       0.59      0.43      0.47       320
weighted avg       0.71      0.72      0.71       320



RandomForestClassifier()

In [41]:
# to deal with overfitting applying pruning techiques
mymodel(DecisionTreeClassifier(max_depth=15,min_samples_split=12))

Training Score : 0.8577013291634089
Testing Score : 0.56875
Confusion Matrix : 
[[ 0  0  1  0  0  0]
 [ 2  1  7  3  0  0]
 [ 1  6 97 31  5  0]
 [ 0  1 46 69 18  0]
 [ 0  0  5 10 15  0]
 [ 0  0  0  0  2  0]]
Classification Report : 
              precision    recall  f1-score   support

           3       0.00      0.00      0.00         1
           4       0.12      0.08      0.10        13
           5       0.62      0.69      0.66       140
           6       0.61      0.51      0.56       134
           7       0.38      0.50      0.43        30
           8       0.00      0.00      0.00         2

    accuracy                           0.57       320
   macro avg       0.29      0.30      0.29       320
weighted avg       0.57      0.57      0.56       320



DecisionTreeClassifier(max_depth=15, min_samples_split=12)

In [ ]:
# imbalanced data-- stratify

In [44]:
pip install imbalanced-learn

Note: you may need to restart the kernel to use updated packages.


In [48]:
from imblearn.over_sampling import RandomOverSampler
ros = RandomOverSampler(random_state=0)
xsample,ysample=ros.fit_resample(xtrain,ytrain)
ysample.value_counts()

quality
6    541
5    541
7    541
4    541
8    541
3    541
Name: count, dtype: int64

In [52]:
model=DecisionTreeClassifier(max_depth=15,min_samples_split=12)
model.fit(xsample,ysample)
ypred=model.predict(xtest)
train_score=model.score(xsample,ysample)
test_score=model.score(xtest,ytest)
print(f"Training Score : {train_score}")
print(f"Testing Score : {test_score}")
print(f"Confusion Matrix : \n{confusion_matrix(ytest,ypred)}")
print(f"Classification Report : \n{classification_report(ytest,ypred)}")


Training Score : 0.9516327788046827
Testing Score : 0.603125
Confusion Matrix : 
[[  0   0   0   1   0   0]
 [  1   3   5   4   0   0]
 [  3   2 102  24   9   0]
 [  0   4  35  70  21   4]
 [  0   0   4   9  17   0]
 [  0   0   0   0   1   1]]
Classification Report : 
              precision    recall  f1-score   support

           3       0.00      0.00      0.00         1
           4       0.33      0.23      0.27        13
           5       0.70      0.73      0.71       140
           6       0.65      0.52      0.58       134
           7       0.35      0.57      0.44        30
           8       0.20      0.50      0.29         2

    accuracy                           0.60       320
   macro avg       0.37      0.42      0.38       320
weighted avg       0.63      0.60      0.61       320



In [68]:
model=RandomForestClassifier(n_estimators=80,max_depth=25,min_samples_split=9)
model.fit(xsample,ysample)
ypred=model.predict(xtest)
train_score=model.score(xsample,ysample)
test_score=model.score(xtest,ytest)
print(f"Training Score : {train_score}")
print(f"Testing Score : {test_score}")
print(f"Confusion Matrix : \n{confusion_matrix(ytest,ypred)}")
print(f"Classification Report : \n{classification_report(ytest,ypred)}")

Training Score : 0.9941466420209488
Testing Score : 0.690625
Confusion Matrix : 
[[  0   0   1   0   0   0]
 [  1   0   9   2   1   0]
 [  1   1 114  22   2   0]
 [  0   1  29  88  16   0]
 [  0   0   3   9  18   0]
 [  0   0   0   0   1   1]]
Classification Report : 
              precision    recall  f1-score   support

           3       0.00      0.00      0.00         1
           4       0.00      0.00      0.00        13
           5       0.73      0.81      0.77       140
           6       0.73      0.66      0.69       134
           7       0.47      0.60      0.53        30
           8       1.00      0.50      0.67         2

    accuracy                           0.69       320
   macro avg       0.49      0.43      0.44       320
weighted avg       0.67      0.69      0.68       320



In [93]:
def multi_to_binary(x):
    if x<=5:
        return 0
    else:
        return 1

In [95]:
df["quality_binary"]=df["quality"].apply(multi_to_binary)
df["quality_binary"].value_counts()

quality_binary
1    855
0    744
Name: count, dtype: int64

In [97]:
features=df.drop(['quality',"quality_binary"],axis=1)
target=df["quality_binary"]

In [99]:
xtrain,xtest,ytrain,ytest=train_test_split(features,target,test_size=0.2,random_state=1)

In [101]:
mymodel(DecisionTreeClassifier(max_depth=15,min_samples_split=12))

Training Score : 0.9319781078967944
Testing Score : 0.76875
Confusion Matrix : 
[[118  36]
 [ 38 128]]
Classification Report : 
              precision    recall  f1-score   support

           0       0.76      0.77      0.76       154
           1       0.78      0.77      0.78       166

    accuracy                           0.77       320
   macro avg       0.77      0.77      0.77       320
weighted avg       0.77      0.77      0.77       320



DecisionTreeClassifier(max_depth=15, min_samples_split=12)

In [105]:
mymodel(RandomForestClassifier(n_estimators=80,max_depth=15,min_samples_split=12))

Training Score : 0.9554339327599687
Testing Score : 0.815625
Confusion Matrix : 
[[125  29]
 [ 30 136]]
Classification Report : 
              precision    recall  f1-score   support

           0       0.81      0.81      0.81       154
           1       0.82      0.82      0.82       166

    accuracy                           0.82       320
   macro avg       0.82      0.82      0.82       320
weighted avg       0.82      0.82      0.82       320



RandomForestClassifier(max_depth=15, min_samples_split=12, n_estimators=80)