In [2]:
l=[]
for i in range(5):
    l.append(int(input("Enter a number : ")))
print(l)
#----------------------
m=[]
for i in l:
    m.append(i*3)
print(m)   
#----------------
n=[i*3 for i in l]
print(n)
#-----------------
f=lambda x:x*3
a=list(map(f,l))
print(a)
#--------------------------------------------------
#--------------------------------------------------
e=[i*3  for i in l if i%2==0]
print(e)
#--------------------
f=lambda x:x%2==0
a=list(filter(f,l))
b=list(map(lambda d:d*3,a))
print(b)
#---------------------
c=list(map(lambda d:d*3,filter(lambda x:x%2==0,l)))
print(c)

Enter a number :  2
Enter a number :  3
Enter a number :  4
Enter a number :  5
Enter a number :  6


[2, 3, 4, 5, 6]
[6, 9, 12, 15, 18]
[6, 9, 12, 15, 18]
[6, 9, 12, 15, 18]
[6, 12, 18]
[6, 12, 18]
[6, 12, 18]


In [9]:
import numpy as np

In [4]:
n=np.array([1,2,3,4,5])
print(n)
print(type(n))
print(n.dtype)
print(n.shape)
m=n.astype("float")
print(m.dtype)
print(m)
print(n*3) # broadcasting

[1 2 3 4 5]
<class 'numpy.ndarray'>
int64
(5,)
float64
[1. 2. 3. 4. 5.]
[ 3  6  9 12 15]


In [5]:
n=np.zeros((4,3))
print(n)
print(type(n))
print(n.dtype)
print(n.shape)
n=np.ones((2,3)).astype(int)
print(n)
print(type(n))
print(n.dtype)
print(n.shape)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
<class 'numpy.ndarray'>
float64
(4, 3)
[[1 1 1]
 [1 1 1]]
<class 'numpy.ndarray'>
int64
(2, 3)


In [6]:
n=np.arange(10,101,10)
print(n)
print(type(n))
print(n[2:6]) #30  40  50  60  70
print(n[1:9:2]) # 20, 40, 60,80,100 | 

n=np.linspace(2,9,7)
print(n)

[ 10  20  30  40  50  60  70  80  90 100]
<class 'numpy.ndarray'>
[30 40 50 60]
[20 40 60 80]
[2.         3.16666667 4.33333333 5.5        6.66666667 7.83333333
 9.        ]


In [7]:
n=np.arange(10,101,10).reshape(5,2)
print(n)
print(n.shape)
print(n.ndim)
print(n.size)
n=np.arange(10,101,10).reshape(2,5)
print(n)
print(n.shape)
print(n.ndim)
print(n.size)

[[ 10  20]
 [ 30  40]
 [ 50  60]
 [ 70  80]
 [ 90 100]]
(5, 2)
2
10
[[ 10  20  30  40  50]
 [ 60  70  80  90 100]]
(2, 5)
2
10


In [8]:
m=np.arange(1,11).reshape(2,5)
print(m)
print(m.shape)
print(m.ndim)
print(m.size)
print(n+m)
print(n-m)
print(n*m)
print(n/m)
print(n//m)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
(2, 5)
2
10
[[ 11  22  33  44  55]
 [ 66  77  88  99 110]]
[[ 9 18 27 36 45]
 [54 63 72 81 90]]
[[  10   40   90  160  250]
 [ 360  490  640  810 1000]]
[[10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10.]]
[[10 10 10 10 10]
 [10 10 10 10 10]]


In [15]:
a=np.arange(1,11).reshape(5,2)
print(a)
print(a.shape)
print(a.ndim)
print(a.max(),a.min(),a.std(),a.var(),a.mean(),np.sqrt(a),np.log(a))

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
(5, 2)
2
10 1 2.8722813232690143 8.25 5.5 [[1.         1.41421356]
 [1.73205081 2.        ]
 [2.23606798 2.44948974]
 [2.64575131 2.82842712]
 [3.         3.16227766]] [[0.         0.69314718]
 [1.09861229 1.38629436]
 [1.60943791 1.79175947]
 [1.94591015 2.07944154]
 [2.19722458 2.30258509]]


In [28]:
a=np.arange(1,5).reshape(2,2)
b=np.arange(11,15).reshape(2,2)
c=np.concatenate((a,b),axis=0)
d=np.concatenate((a,b),axis=1)
print(c)
print(d)
e=a.reshape((4,))
print(e)
print(np.split(e,2))

[[ 1  2]
 [ 3  4]
 [11 12]
 [13 14]]
[[ 1  2 11 12]
 [ 3  4 13 14]]
[1 2 3 4]
[array([1, 2]), array([3, 4])]


In [40]:
a=np.arange(1,17).reshape(4,4)
print(a)
print("---------")
print(a[1])
print(a[1:3,:])
print(a[:,1:3])
print(a[1:3,1:3])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
---------
[5 6 7 8]
[[ 5  6  7  8]
 [ 9 10 11 12]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
[[ 6  7]
 [10 11]]


In [46]:
a=np.array([1,2,3])
b=np.insert(a,2,[4,5,6,7,8])
print(b)
b=np.append(b,[20,30,40,50,60])
print(b)
a=np.delete(b,[2,3,4,5])
print(a)

[1 2 4 5 6 7 8 3]
[ 1  2  4  5  6  7  8  3 20 30 40 50 60]
[ 1  2  8  3 20 30 40 50 60]


In [48]:
a=np.arange(20,30).reshape(5,2)
print(a)
b=a.flatten()
print(b)

[[20 21]
 [22 23]
 [24 25]
 [26 27]
 [28 29]]
[20 21 22 23 24 25 26 27 28 29]


In [49]:
a+1 # broadcasting

array([[21, 22],
       [23, 24],
       [25, 26],
       [27, 28],
       [29, 30]])

In [51]:
a=np.arange(1,5).reshape(2,2)
print(a)
b=np.arange(11,15).reshape(2,2)
print(b)
a+b # vectorization

[[1 2]
 [3 4]]
[[11 12]
 [13 14]]


array([[12, 14],
       [16, 18]])

In [54]:
a=np.arange(20,30)
print(a)
print(a>25)
print(a[a>25])

[20 21 22 23 24 25 26 27 28 29]
[False False False False False False  True  True  True  True]
[26 27 28 29]


In [65]:
a=np.random.randint(10)
b=int(input("Enter number between 0 and 10 : "))
count=1
while True:
    if a==b:
        print(f"Guessed the right number in count {count}")
        break
    else:
        b=int(input("Enter number : "))
        count+=1
    

Enter number :  9
Enter number :  5
Enter number :  2
Enter number :  4
Enter number :  1


Guessed the right number in count 5


In [69]:
a=np.arange(1,17).astype("float").reshape(4,4)
print(a)
b=np.delete(a,1,axis=1)
print(b)
c=np.where(b>7,"High","Low")
print(c)

[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]
 [13. 14. 15. 16.]]
[[ 1.  3.  4.]
 [ 5.  7.  8.]
 [ 9. 11. 12.]
 [13. 15. 16.]]
[['Low' 'Low' 'Low']
 ['Low' 'Low' 'High']
 ['High' 'High' 'High']
 ['High' 'High' 'High']]


In [77]:
a=np.zeros((2,2))
print(a)
np.fill_diagonal(a,7)
print(a)

[[0. 0.]
 [0. 0.]]
[[7. 0.]
 [0. 7.]]


In [79]:
a=np.arange(20,50)
print(a)
print(a[(a%7==0)|(a%3==0)])
print(a[(a%7==0)&(a%3==0)])

[20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43
 44 45 46 47 48 49]
[21 24 27 28 30 33 35 36 39 42 45 48 49]
[21 42]


In [82]:
a=np.array([1,23,34,22,-1,-1,3,2,-1])
valid_data=a[a!=-1]
print(valid_data)
a[a==-1]=np.mean(valid_data)
print(a)

[ 1 23 34 22  3  2]
[ 1 23 34 22 14 14  3  2 14]


In [84]:
a=np.array([1,2,3,4,5])
b=np.array([2,1,3,5,4])
print("Difference between a and b",a-b)
print("Number of times a>b ",np.sum(a>b))

Difference between a and b [-1  1  0 -1  1]
Number of times a>b  2
