In [1]:
#!pip install numpy

### 
Numpy

In [3]:
import numpy as np

In [4]:
l=[1,2,3,4]
print(l)
print(type(l))
print(l*3) # concatenation

m=[]
for i in l:
    m.append(i*3)
print(m)

m=[i*3 for i in l]
print("m",m)

[1, 2, 3, 4]
<class 'list'>
[1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]
[3, 6, 9, 12]
m [3, 6, 9, 12]


In [5]:
n=np.array(l)

print(n)
print(type(n))
n=n*3
print(m)

[1 2 3 4]
<class 'numpy.ndarray'>
[3, 6, 9, 12]


In [6]:
l=["A",True,None,10]
print(l)
print(type(l))
print(l*3)

['A', True, None, 10]
<class 'list'>
['A', True, None, 10, 'A', True, None, 10, 'A', True, None, 10]


In [7]:
l=["A","B","C"] #
n=np.array(l)
print(n)
print(type(n))
#print(n*3) ------ error. Numpy arrays works on numbers and not on mixed datatype 

['A' 'B' 'C']
<class 'numpy.ndarray'>


In [8]:
#n=np.array([[1,2,3],[4,5,6]])
n=np.array([1,2,3,4,5])
print(n)
print(type(n))
print("Shape",n.shape)
print("Dimension",n.ndim)

[1 2 3 4 5]
<class 'numpy.ndarray'>
Shape (5,)
Dimension 1


In [9]:
# broadcasting
n=np.array([1,2,3,4,5])
print(n*5)
print("-------------")
n=np.array([[1,2,3],[4,5,6]])
m=np.array([10,20,30])
print(n+m)

[ 5 10 15 20 25]
-------------
[[11 22 33]
 [14 25 36]]


In [10]:
n=np.zeros((2,2)) # np.ones
print(n)
print(type(n))
print("Shape",n.shape)
print("Dimension",n.ndim)

[[0. 0.]
 [0. 0.]]
<class 'numpy.ndarray'>
Shape (2, 2)
Dimension 2


In [11]:
u=np.random.rand() # random float number
print(u)
u=np.random.rand(3,3) # random float array
print(u)
u=np.random.randint(1,10) # random integer number between 1 to 10
print(u)
u=np.random.randint(1,10,size=(5,3)) # random integer array
print(u)

0.7830246036135486
[[0.83385599 0.62142114 0.05162872]
 [0.72525713 0.20636675 0.52222113]
 [0.51454167 0.53359705 0.55350528]]
3
[[9 3 3]
 [2 6 1]
 [9 7 6]
 [4 2 8]
 [6 9 1]]


In [12]:
n=np.array([[1,2,3],[4,5,6]])
print(n)
print("Shape",n.shape)
m=n.T
print(m)
print("Shape",m.shape)

[[1 2 3]
 [4 5 6]]
Shape (2, 3)
[[1 4]
 [2 5]
 [3 6]]
Shape (3, 2)


In [13]:
n=np.array([[1,2,3],[4,5,6]])
print(n)
print("Shape",n.shape)
m=n.reshape(6,1)
print(m)
print("Shape",m.shape)
m=n.reshape(1,6)
print(m)
print("Shape",m.shape)
m=n.reshape(3,2)
print(m)
print("Shape",m.shape)

[[1 2 3]
 [4 5 6]]
Shape (2, 3)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
Shape (6, 1)
[[1 2 3 4 5 6]]
Shape (1, 6)
[[1 2]
 [3 4]
 [5 6]]
Shape (3, 2)


In [14]:
n=np.array([1,2,3,4,5,6]).reshape(2,3)
m=np.array([7,8,9,1,2,3]).reshape(2,3)
a=np.concatenate((n,m),axis=0)
print(a)
print(a.shape)
a=np.concatenate((n,m),axis=1)
print(a)
print(a.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]
 [1 2 3]]
(4, 3)
[[1 2 3 7 8 9]
 [4 5 6 1 2 3]]
(2, 6)


In [15]:
n=np.array([1,2,3,4,5,6]).reshape(2,3)
m=np.array([7,8,9,1,2,3]).reshape(2,3)
a=np.vstack((n,m))
print(a)
a=np.hstack((n,m))
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]
 [1 2 3]]
[[1 2 3 7 8 9]
 [4 5 6 1 2 3]]


In [16]:
n=np.array([1,2,3,4,5,6],dtype="float").reshape(2,3)
n

array([[1., 2., 3.],
       [4., 5., 6.]])

In [17]:
n=np.array([1,2,3]) 
print(n)
a=np.append(n,[4,5,6,7]) # added elements at the end
print(a)
i=np.insert(a,2,[10,11,12,13,14]) # added elements at the given index
print(i)
d=np.delete(i,[2,3,4,5]) # deletes numbers on the mentioned indexes
print(d)

[1 2 3]
[1 2 3 4 5 6 7]
[ 1  2 10 11 12 13 14  3  4  5  6  7]
[ 1  2 14  3  4  5  6  7]


In [18]:
a=np.arange(1,11,2)
a

array([1, 3, 5, 7, 9])

In [19]:
a=np.arange(20,30).reshape(5,2) # method chaining
print(a)
#25 --
print(a[1,1]) # indexing

[[20 21]
 [22 23]
 [24 25]
 [26 27]
 [28 29]]
23


In [20]:
b=np.arange(1,17).reshape(4,4)
print(b)
# [[6 7]
#   [10 11]]
print(b[1:3,:]) # slicing

print(b[:,1:3])
print(b[1:3,1:3])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[ 5  6  7  8]
 [ 9 10 11 12]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
[[ 6  7]
 [10 11]]


In [21]:
b=np.arange(1,7).reshape(2,3)
print(b)
print(b.sum(),b.mean(),b.std(),b.var(),b.prod(),b.max(),b.min(),b.cumsum())
# sum is giving total, mean-- average,std--standard deviation,var -- variance



[[1 2 3]
 [4 5 6]]
21 3.5 1.707825127659933 2.9166666666666665 720 6 1 [ 1  3  6 10 15 21]


In [22]:
a=np.array([1,2,3,4]).reshape(2,2)
b=np.array([1,2,3,4]).reshape(2,2)
print(a+b)
print(a*b)

[[2 4]
 [6 8]]
[[ 1  4]
 [ 9 16]]


In [45]:
np.dot(a,b)

array([[ 7, 10],
       [15, 22]])