In [58]:
import numpy as np #

In [59]:
'''
l=[1,2,3,4]
l1=[]
for i in l:
    l1.append(i*3)
print(l1) 
'''
l=[1,2,3,4]
l1=[i*3 for i in l]
print(l1)
l=l1
print(l)

[3, 6, 9, 12]
[3, 6, 9, 12]


In [60]:
l=[1,"ABC","A",True]
print(l*3)
type(l)

[1, 'ABC', 'A', True, 1, 'ABC', 'A', True, 1, 'ABC', 'A', True]


list

In [61]:
l=[1,2,3,4]
n=np.array([1,2,3,4])
print(type(n))
print(n)
print(n*3)

<class 'numpy.ndarray'>
[1 2 3 4]
[ 3  6  9 12]


In [62]:
'''
Why we use numpy? 
'''

'\nWhy we use numpy? \n'

In [63]:
print(n)
print(n.dtype)
n=np.array([1.0,2.0,3,4])
print(n)
print(n.dtype)
print(n*3)
print(n.shape)

[1 2 3 4]
int32
[1. 2. 3. 4.]
float64
[ 3.  6.  9. 12.]
(4,)


In [64]:
n

array([1., 2., 3., 4.])

In [65]:
l=[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]
n=np.array(l)
print(n.shape)
print(n.ndim)

(4, 3)
2


In [66]:
a=np.zeros((4,4))
print(a)
print(a.shape)
print(a.ndim)
a=np.ones((4,4))
print(a)
print(a.shape)
print(a.ndim)
a=np.arange(0,10)
print(a)
print(a.shape)
print(a.ndim)
a=np.arange(0,100,10)
print(a)
print(a.shape)
print(a.ndim)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
(4, 4)
2
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
(4, 4)
2
[0 1 2 3 4 5 6 7 8 9]
(10,)
1
[ 0 10 20 30 40 50 60 70 80 90]
(10,)
1


In [67]:
# arithemtic operations
a=np.arange(1,7).reshape((3,2)) 
print(a)
print(a.shape)
print(a.ndim)
b=np.arange(8,14).reshape((3,2))
print(a+b)
print(a/b)
print(a**2)

[[1 2]
 [3 4]
 [5 6]]
(3, 2)
2
[[ 9 11]
 [13 15]
 [17 19]]
[[0.125      0.22222222]
 [0.3        0.36363636]
 [0.41666667 0.46153846]]
[[ 1  4]
 [ 9 16]
 [25 36]]


In [68]:
# aggregation operations--
a=np.arange(1,7)
print(a)
print(a.sum())
print(a.mean())
a=np.arange(1,7).reshape((3,2)) 
print(a)
print(a.sum())
print(a.mean())
print(a.max())
print(a.min())

[1 2 3 4 5 6]
21
3.5
[[1 2]
 [3 4]
 [5 6]]
21
3.5
6
1


In [69]:
# broadcasting
a=np.array([[2,3],[4,5],[6,7]])
b=np.array([10,20])
print(a+b)
#vectorization

[[12 23]
 [14 25]
 [16 27]]


In [70]:
# mathematical functions
n=np.array([1,2,3,4,5])
print(np.sqrt(n))
print(np.log(n))
print(np.exp(n))

[1.         1.41421356 1.73205081 2.         2.23606798]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


In [71]:
# conctenate
a=np.arange(1,5).reshape((2,2))
b=np.arange(10,14).reshape((2,2))
print(np.concatenate((a,b),axis=0))
print(np.concatenate((a,b),axis=1))

[[ 1  2]
 [ 3  4]
 [10 11]
 [12 13]]
[[ 1  2 10 11]
 [ 3  4 12 13]]


In [72]:
# splitting
a=np.arange(1,7).reshape((6,))
print(a)
np.split(a,2)

[1 2 3 4 5 6]


[array([1, 2, 3]), array([4, 5, 6])]

In [73]:
i=65
chr(i)

'A'

In [74]:
for i in range(0,5):
    for j in range(64,65+i):
        a=65+i
        print(chr(a),end=" ")
    print()

A 
B B 
C C C 
D D D D 
E E E E E 


In [94]:
a=np.arange(1,17).reshape(4,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [106]:
a=np.arange(1,17).reshape(16,)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [112]:
a[::-2]

array([16, 14, 12, 10,  8,  6,  4,  2])

In [114]:
a[-3]

14

In [116]:
a[3]

4

In [118]:
a[1:9:2]

array([2, 4, 6, 8])

In [120]:
a=np.arange(1,17).reshape(4,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [122]:
a[1:3,:]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [124]:
a[:,1:3]

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [126]:
a[1:3,1:3]

array([[ 6,  7],
       [10, 11]])

In [128]:
a=np.array([1,2,3])
a

array([1, 2, 3])

In [134]:
a=np.append(a,[4,5,6,7,8])
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [136]:
a=np.insert(a,2,[10,11,12,13])
a

array([ 1,  2, 10, 11, 12, 13,  3,  4,  5,  6,  7,  8])

In [138]:
a=np.delete(a,[2,3,4,5]) #
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [148]:
a=np.arange(20,30).reshape(5,2)
print(a)
print(a.shape)
a=a.flatten()
print(a)
print(a.shape)

[[20 21]
 [22 23]
 [24 25]
 [26 27]
 [28 29]]
(5, 2)
[20 21 22 23 24 25 26 27 28 29]
(10,)


In [154]:
a[a>25]

array([26, 27, 28, 29])

In [158]:
names=np.array(["Harry","Tom","Bob","Harry","Potter","Yash","Adarsh","Harry"])
names[names=="Harry"]

array(['Harry', 'Harry', 'Harry'], dtype='<U6')

In [164]:
names[(names=="Tom")|(names=="Bob")] # & and | or

array(['Tom', 'Bob'], dtype='<U6')

In [170]:
a=np.array([[1,2],[3,4]])
b=np.array([[1,2],[3,4]])
print(a+b)
#print(a*b)
print(np.dot(a,b))

[[2 4]
 [6 8]]
[[ 7 10]
 [15 22]]


In [200]:
a=np.random.randint(10)
while True:
    i=int(input("Enter a number from 0-10"))
    if i==a:
        print("Its a match")
        break
    else:
        print("Not a match")

Enter a number from 0-10 0


Not a match


Enter a number from 0-10 1


Not a match


Enter a number from 0-10 2


Not a match


Enter a number from 0-10 3


Not a match


Enter a number from 0-10 4


Not a match


Enter a number from 0-10 5


Its a match


In [222]:
a=np.random.randint(1,11,size=[5])
a

array([6, 8, 3, 4, 9])

In [226]:
a=np.random.randn(5,2)
a

array([[ 0.42622546,  0.80032387],
       [-0.7033467 ,  0.85796896],
       [-0.06262511,  1.26939215],
       [-0.43264187, -0.3258603 ],
       [ 0.17640491, -2.47340511]])

In [ ]:
r'https:\\docs.python.org\3\library\re.html'

In [228]:
import re

In [348]:
text="12 There are12 apples,345 bananas and 7890 oranges in a basket"
text

'12 There are12 apples,345 bananas and 7890 oranges in a basket'

In [350]:
pattern=re.compile(r'\b\d{2,3}\b')
re.findall(pattern,text)

['12', '345']